# Generated by Django 5.0.6 on 2024-06-03 15:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfind_core', '0002_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=512)),
                ('engine_size', models.IntegerField(default=0)),
                ('engine_power', models.IntegerField(default=0)),
                ('production_date', models.DateField(default=datetime.datetime(2024, 6, 3, 17, 57, 4, 120416))),
                ('publication_date', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 17, 57, 4, 120416))),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfind_core.enginetype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carfind_core.model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
