# Generated by Django 5.0.6 on 2024-06-04 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfind_core', '0003_enginetype_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='offer',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='production_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 11, 24, 31, 941158)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 11, 24, 31, 941158)),
        ),
    ]
