# Generated by Django 5.0.6 on 2024-06-04 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carfind_core', '0004_offer_location_offer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMain', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='production_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 4, 17, 40, 31, 189171)),
        ),
        migrations.AlterField(
            model_name='offer',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 4, 17, 40, 31, 189171)),
        ),
    ]
